### ISSUE TITLE
支持ant design vue3的表格吗？

### ISSUE THREAD

**Issue by batsx** [Lionad-Morotar/use-scrollbar#2]
### Description

支持ant design vue3的表格吗？

### Validations

- [X] Read the [Readme](https://github.com/Lionad-Morotar/use-scrollbar).
- [X] Check that there isn't [already an issue](https://github.com/Lionad-Morotar/use-scrollbar/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Lionad-Morotar/use-scrollbar/discussions).

**Comment by Lionad-Morotar** [comment]
AntTable 默认使用 windows 滚动条：
![image](https://github.com/Lionad-Morotar/use-scrollbar/assets/26913795/18348547-b3b4-4b13-b60c-c9ab4c3ab731)

使用 UseScrolls 美化滚动条后：
![image](https://github.com/Lionad-Morotar/use-scrollbar/assets/26913795/732c70a1-3af0-4dea-8d4e-13a8348577bb)

**Comment by Lionad-Morotar** [comment]
示例代码可以参考：[https://github.com/Lionad-Morotar/use-scrollbar/blob/HEAD/play/src/ant-vue-table.vue](https://github.com/Lionad-Morotar/use-scrollbar/blob/HEAD/play/src/ant-vue-table.vue) ~
