### ISSUE TITLE
后续是否支持Vue2版本

### ISSUE THREAD

**Issue by wangdaodao** [Lionad-Morotar/use-scrollbar#3]
### Description

请问后续还支持Vue2的版本吗？

### Validations

- [X] Read the [Readme](https://github.com/Lionad-Morotar/use-scrollbar).
- [X] Check that there isn't [already an issue](https://github.com/Lionad-Morotar/use-scrollbar/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Lionad-Morotar/use-scrollbar/discussions).

**Comment by Lionad-Morotar** [comment]
会支持 Vue2 和提供相应的示例，也欢迎 PR ~

**Comment by wangdaodao** [comment]
感谢，后续我会持续关注
